hello:
  pattern: "Hello there, %s!"

swagger:
  baseApiPackage: "com.ibm.hello"
  title: "Sample API Documentation"
  description: "Description"
  version: "0.1.0"
  termsOfServiceUrl: ""
  contact:
    name: "John Doe"
    email: "johndoe@ibm.com"
  license: "MIT"
  licenseUrl: ""

management:
  endpoints:
    web:
      base-path: "/metrics"
      exposure:
        include: "*"

server:
  port: 9080
